.github/workflows/ci.yml, dependency/cpp.requirements.txt
Currently, all dependencies were pointing to dev which is a moving target.
=> Move all versions of software to stable releases

src/dlio_profiler/core/dlio_profiler_main.cpp, src/dlio_profiler/utils/posix_internal.cpp, src/dlio_profiler/utils/posix_internal.h, src/dlio_profiler/writer/chrome_writer.cpp, test/CMakeLists.txt, test/check_file.sh
Added check for json files.
Fixes #33 
Fixes #31
=> Added capability to check json file in test case.

dlio_profiler/logger.py
=> change all args to string based.

docs/building_applications.rst, docs/index.rst
Adding a page for building programs with DLIO Profiler using Makefile.
=> Adding page for building programs with dlio-profiler using Makefile

src/dlio_profiler/core/dlio_profiler_main.cpp
The PR fixes cleaning of file that were not written to.
=> fixed cleaning incomplete file.

examples/dlp_analyzer/requirements.txt
=> Added bokeh plot for timeline

src/dlio_profiler/writer/chrome_writer.cpp
Fixed conversion of string to char* for logging.
=> Fixed conversion of string to char* for logging.

dependency/CMakeLists.txt, src/dlio_profiler/core/dlio_profiler_main.cpp
extensions should have . character
=> Fix extension ignore list

docs/index.rst, docs/migration.rst
This PR adds a migration documentation from DLIO Profiler to DFTracer.
=> Migration documentation from DLIO Profiler to DFTracer

dfanalyzer/main.py
For wierd files, the json conversion has issues. 
This will make sure all strings are unicode
=> Convert line into unicode

README.md
In this PR, we improve the Readme by
=> Improving Readme

dfanalyzer/dask/scripts/start_dask_distributed.sh, docs/dfanalyzer_alcf_polaris.rst
This PR fixes a bug in the scripts which expects the log dir and run dir to exist.
=> Improve dask scripts to create log dir and run dir automatically.

docs/dfanalyzer_distributed.rst, docs/index.rst
Added documentation for dask distributed.
=> Add dask distributed doc

CMakeLists.txt, cmake/configure_files/dftracer-config.cmake.build.in, cmake/configure_files/dftracer-config.cmake.install.in
During refactoring some installtion bugs came in for find package. I fixed those.
=> Fix installation bugs during refactoring

dfanalyzer/plots.py, setup.py
- fixed seaborn
- added option to change formatter for yaxis.
=> Fixed a new package which is used

dfanalyzer/plots.py
- fixed args
- fixed sorting of functions
=> fixed plotting

docs/dfanalyzer_build.rst
Added simple docs for DFAnalyzer notebook
=> Fixed documentation for simple dfanalyzer

CMakeLists.txt, script/dftracer_compact.sh
This PR adds two scripts to install folder.
1. merge_pfw which takes multiple files and merges them into 1
2. dftracer_compact which take multiple files and creates a even set of files with n lines each.
=> Installation of scripts for combining pfw files and compacting them

docs/bash_utilities.rst, docs/index.rst, docs/requirements.txt, docs/utilities.rst, script/dftracer_compact.sh, script/merge_pfw.sh
1. merge_pfw: This script allows users to combine all pfw format into one. 
2. dftracer_compact: The script compacts all trace file and then divides the trace into equal file pieces.
3. Added bash scripts to parse logs quickly using bash utilities.
=> Added documentations for scripts and added args.

README.md
Added citations and acknowledgement
=> Added citations and acknowledgement

docs/dfanalyzer_overlap_analysis.rst
I had some mistakes in writing example code of overlap analysis
Hopefully this will give reader clear information on how to do overlap analysis
=> fix typo in overlap analysis code

MANIFEST.in, dfanalyzer/main.py
This PR enhances the summary to check time skew across nodes (hariharan-devarajan Fixes #160 )
=> Enhance: Check time skew across nodes (hariharan-devarajan#160)

include/dftracer/core/typedef.h, include/dftracer/dftracer.h, src/dftracer/brahma/posix.cpp, src/dftracer/brahma/stdio.cpp, src/dftracer/core/dftracer_main.cpp, src/dftracer/core/dftracer_main.h, src/dftracer/core/enumeration.h, src/dftracer/df_logger.h, src/dftracer/dftracer.cpp, src/dftracer/writer/chrome_writer.cpp, src/dftracer/writer/chrome_writer.h
Now we have the capability to change process name to use rank if present.
=> Changes to support metadata events for using Rank information for processes

dfanalyzer/main.py
The current indexing was missing last event
=> Bugfix: including last event from file.

dftracer_dbg/logger.py
We wrongly used the "image-size" for "step" args
=> fix typo in args dftracer log

docs/index.rst, docs/trace_format.rst
=> Documentation: Added trace format in documentations.

dftracer/logger.py, dftracer_dbg/logger.py
I added support to disable the whole category of profiling by adding `enable` params on the `dft_fn`
=> Add conditional disabling of dft_fn categories

docs/api.rst
=> Documentation: Fix Environment Variables

src/dftracer/brahma/posix.cpp, src/dftracer/brahma/posix.h
Bugfix: Fix for handle AT_FDCWD for readlinkat
=> Bugfix: Fix for handle AT_FDCWD for readlinkat

CITATION.cff
=> Repository: Add DOI to CITATION.cff

docs/api.rst, docs/examples.rst
- added warning in `example.rst`
- added warning in `api.rst`
=> add warning for `DFTRACER_DATA_DIR`

docs/build.rst
The docs for installation require the following fixes.
=> Updated build instructions

.github/workflows/ci.yml, setup.py
This makes sure it works with GCC 13
=> BugFix: We need to build symbols of dftracer for GCC-13

CMakeLists.txt, docs/utilities.rst, script/dftracer_pgzip, setup.py
Added a new utility for doing per file gzip in parallel.
=> Added parallel gzip
